repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.27
    hooks:
      - id: actionlint
  - repo: https://github.com/warchant/pre-commit-buildifier
    rev: 0.1.1
    hooks:
      - id: buildifier
